apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec: 
      volumes: 
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: password 
            - name: POSTGRES_USER
              value: admin
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-claim
      restartPolicy: Always
    
  